# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: uncompiled
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: alexa-fruit-stand
service: alexa-fruit-stand
provider:
  name: aws
  runtime: nodejs24.x
  stage: v2
  region: us-east-1
package:
  patterns:
    - src/**
    - node_modules/pluralize/**
    - '!.git/**'
    - '!.github/**'
    - '!.serverless/**'
    - '!icons/**'
    - '!speechAssets/**'
    - '!test/**'
functions:
  skill:
    handler: src/index.handler
    logRetentionInDays: 1
